#!/bin/bash
# Assembles the pixel programs in shaders_src/ and packs each into a shader
# container, writing shaders_build/<name>_sb.h for the C code to embed.
#
# The container is made here from SharpProspero's mesh pixel program
# (third_party/sharpprospero/mesh_ps.sb, GPL-3.0): agcpack.py texture-container
# declares in it the texture and sampler every program here reads. The vertex
# program is SharpProspero's mesh_vs.sb as it is.
#
# Each entry names the output, the source, the VGPRS to declare in the
# container's SPI_SHADER_PGM_RSRC1_PS, and any further options for agcpack,
# such as --or-reg to set bits in a header register.
#
# Needs llvm-mc and llvm-objcopy built with the amdgcn target (Ubuntu's LLVM 18
# has it); LLVM_MC and LLVM_OBJCOPY name them if they are not on the PATH.
set -e
here=$(cd "$(dirname "$0")" && pwd)
out=$here/shaders_build
third=$here/third_party/sharpprospero
LLVM_MC=${LLVM_MC:-llvm-mc}
LLVM_OBJCOPY=${LLVM_OBJCOPY:-llvm-objcopy}
mkdir -p "$out"

python3 "$here/shader_tools/agcpack.py" texture-container "$third/mesh_ps.sb" "$out/texture_container.sb"
python3 "$here/shader_tools/agcpack.py" array "$out/mesh_vs_sb.h" mesh_vs_sb "$third/mesh_vs.sb"

build() {
    local name=$1 source=$2 vgprs=$3
    shift 3
    "$LLVM_MC" -triple=amdgcn-amd-amdhsa -mcpu=gfx1030 -filetype=obj -o "$out/$source.o" "$here/shaders_src/$source.s"
    "$LLVM_OBJCOPY" --dump-section .text="$out/$source.bin" "$out/$source.o" "$out/$source.stripped.o"
    python3 "$here/shader_tools/agcpack.py" pack "$out/texture_container.sb" "$out/$source.bin" "$out/$name.sb" --vgprs "$vgprs" "$@"
    python3 "$here/shader_tools/agcpack.py" array "$out/${name}_sb.h" "${name}_sb" "$out/$name.sb"
}

# VGPRS 2 covers v0-v10 only; a program using higher registers declares 4, or
# reads garbage there.
build textured_p         textured_p         2
build water_p            water_p            4
build lava_p             lava_p             4
# SPI_PS_INPUT_ENA and its companion: 0x300 hands the program the fragment's
# position in v2 and v3, as floats. Confirmed on hardware with
# shaders_src/water_vpos_test_p.s, which paints it as a gradient.
build water_reflect_p    water_reflect_p    4  --or-reg 0x1b3=0x300 --or-reg 0x1b4=0x300
# The same program for a scene drawn without supersampling, 1920x1080: its
# place on the scene is the pixel position over half as many pixels each way.
sed -e 's/0\.000260417/0.000520833/' -e 's/0\.000462963/0.000925926/' \
    -e '1i // Generated by build_shaders.sh from water_reflect_p.s for a 1920x1080 scene. Do not edit.' \
    "$here/shaders_src/water_reflect_p.s" > "$here/shaders_src/water_reflect_1x_p.s"
build water_reflect_1x_p water_reflect_1x_p 4  --or-reg 0x1b3=0x300 --or-reg 0x1b4=0x300
# Real shadows: the depth written into the shadow map, and the pass over the
# world that reads it back.
build shadow_depth_p     shadow_depth_p     4
build shadow_recv_p      shadow_recv_p      4
