#!/usr/bin/env python3
"""make_font - renders the options menu's font into a C header.

There is no font renderer on the console, so the glyphs are drawn here, once,
into an atlas: a grid of equal cells, one per character, holding coverage as
alpha. The menu draws each character as a textured quad over its cell and moves
on by the character's own advance, so the text is proportional.

The characters are printable ASCII plus the accented letters Spanish needs.
The last cell is solid, for the menu's panels and bars.

    make_font.py <header out>
"""
import sys

from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
SIZE = 30
COLS = 16
PAD = 3          # empty border in each cell, so bilinear sampling never reaches a neighbour
CHARS = [chr(c) for c in range(32, 127)] + list("áéíóúÁÉÍÓÚñÑüÜ¿¡")
SOLID = 0xFFFF   # the code point the solid cell is filed under


def main(out_path):
    font = ImageFont.truetype(FONT, SIZE)
    ascent, descent = font.getmetrics()
    advances = [int(round(font.getlength(ch))) for ch in CHARS]
    cell_w = max(max(advances), max(font.getbbox(ch)[2] for ch in CHARS)) + 2 * PAD
    cell_h = ascent + descent + 2 * PAD
    glyphs = len(CHARS) + 1
    rows = (glyphs + COLS - 1) // COLS
    tex_w, tex_h = COLS * cell_w, rows * cell_h

    atlas = Image.new("L", (tex_w, tex_h), 0)
    draw = ImageDraw.Draw(atlas)
    for i, ch in enumerate(CHARS):
        # Anchored at the ascender, so every glyph shares one baseline.
        draw.text(((i % COLS) * cell_w + PAD, (i // COLS) * cell_h + PAD), ch, font=font, fill=255)
    solid = len(CHARS)
    x, y = (solid % COLS) * cell_w, (solid // COLS) * cell_h
    draw.rectangle([x, y, x + cell_w - 1, y + cell_h - 1], fill=255)

    codepoints = [ord(ch) for ch in CHARS] + [SOLID]
    advances.append(cell_w)
    alpha = atlas.tobytes()

    def rows_of(values, per_line):
        return ",\n".join("    " + ",".join(str(v) for v in values[i:i + per_line])
                          for i in range(0, len(values), per_line))

    with open(out_path, "w") as out:
        out.write(f"/* Generated by menu_tools/make_font.py from {FONT.split('/')[-1]} at {SIZE}px. Do not edit. */\n")
        out.write(f"#define MENU_FONT_TEX_W {tex_w}\n#define MENU_FONT_TEX_H {tex_h}\n")
        out.write(f"#define MENU_FONT_CELL_W {cell_w}\n#define MENU_FONT_CELL_H {cell_h}\n")
        out.write(f"#define MENU_FONT_COLS {COLS}\n#define MENU_FONT_PAD {PAD}\n")
        out.write(f"#define MENU_FONT_GLYPHS {glyphs}\n#define MENU_FONT_SOLID 0x{SOLID:X}\n")
        out.write(f"static const uint16_t menu_font_codepoints[{glyphs}] = {{\n{rows_of(codepoints, 16)},\n}};\n")
        out.write(f"static const uint8_t menu_font_advance[{glyphs}] = {{\n{rows_of(advances, 16)},\n}};\n")
        out.write(f"static const uint8_t menu_font_alpha[{len(alpha)}] = {{\n{rows_of(list(alpha), 32)},\n}};\n")
    print(f"{out_path}: {glyphs} glyphs, cells {cell_w}x{cell_h}, atlas {tex_w}x{tex_h}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
