#!/usr/bin/env python3
"""make_glyphs - the marks Spanish needs, as textures in the game's own formats.

The game has no accents in the US ROM, so they are drawn here: an acute, a
tilde and a diaeresis, each in the place it takes over a lowercase letter and
over a capital. The letter underneath is the game's own; a mark is simply drawn
on top of it, which is how the European versions do it too.

Two fonts need them:
  - the dialogue font, cells of 8 by 16 pixels, stored as 16 by 8 IA4 textures
    turned on their side (bin/segment2.c, vertex_ia8_char): a pixel at column x
    and row y of the upright cell is the texel (15 - y, 7 - x);
  - the menus' small font, cells of 8 by 8 IA8 the right way up
    (levels/menu/leveldata.c). Its letters fill the whole cell, so its marks are
    drawn four pixels higher, the way the European versions draw an umlaut.

    make_glyphs.py <header out>
"""
import sys

# Where the letters sit in the dialogue font's cell: lowercase from row 7,
# capitals from row 3, both resting on row 12. The font leans, so the marks
# lean with it.
MAIN = {
    "acute_low": [
        "....#...",
        "...#....",
        "..#.....",
    ],                       # rows 4..6
    "acute_high": [
        "....#...",
        "...#....",
        "..#.....",
    ],                       # rows 0..2
    "tilde_low": [
        ".##.#...",
        "#..#....",
    ],                       # rows 5..6
    "tilde_high": [
        ".##.#...",
        "#..#....",
    ],                       # rows 1..2
    "diaeresis_low": [
        ".#.#....",
    ],                       # row 5
    "diaeresis_high": [
        ".#.#....",
    ],                       # row 1
}
# A row of clearance under each mark: without it the acute ran straight into
# the stem of the dotless i and the letter read as something else.
MAIN_TOP = {"acute_low": 3, "acute_high": 0, "tilde_low": 4, "tilde_high": 1,
            "diaeresis_low": 4, "diaeresis_high": 1}

# The small font's marks, in a cell drawn four pixels above the letter's.
MENU = {
    "acute": [
        "....#...",
        "...#....",
        "..#.....",
    ],
    "tilde": [
        "........",
        ".##.#...",
        "#..#....",
    ],
    "diaeresis": [
        "........",
        ".#.#....",
    ],
}
MENU_TOP = {"acute": 0, "tilde": 0, "diaeresis": 1}

# The buttons the dialogues name. The game draws them as bold N64 letters - A,
# B, C, Z - which no one has on a DualSense, so they are drawn as what the
# player actually presses (ps5/controller_ps5.c):
#   [A] cross, [B] square, [C] the right stick, which moves the camera,
#   [Z] the L shoulders. [R] is left as it is: R already reads as R1 and R2.
# Each keeps within the width the game advances by, in the same 2-pixel stroke
# as the letters around it.
BUTTONS = {
    0x54: ("cross", [
        "#.....#.",
        "##...##.",
        ".##.##..",
        "..###...",
        "...#....",
        "..###...",
        ".##.##..",
        "##...##.",
        "#.....#.",
    ], 3),
    0x55: ("square", [
        "#######.",
        "#.....#.",
        "#.....#.",
        "#.....#.",
        "#.....#.",
        "#.....#.",
        "#######.",
    ], 4),
    0x56: ("stick", [
        ".####...",
        "##..##..",
        "#.##.#..",
        "#.##.#..",
        "#....#..",
        "##..##..",
        ".####...",
    ], 4),
    0x57: ("shoulder_l", [
        "##......",
        "##......",
        "##......",
        "##......",
        "##......",
        "##......",
        "##......",
        "##......",
        "##......",
        "######..",
    ], 3),
}


def main_texture(rows, top):
    """A 16 by 8 IA4 texture, 64 bytes, from an upright 8 by 16 drawing."""
    cell = [[0] * 8 for _ in range(16)]
    for r, line in enumerate(rows):
        for c, ch in enumerate(line):
            if ch == '#':
                cell[top + r][c] = 1
    out = bytearray(64)
    for y in range(16):
        for x in range(8):
            if not cell[y][x]:
                continue
            s, t = 15 - y, 7 - x
            i = t * 8 + s // 2
            out[i] |= 0xF0 if s % 2 == 0 else 0x0F
    return out


def menu_texture(rows, top):
    """An 8 by 8 IA8 texture, 64 bytes, the right way up."""
    out = bytearray(64)
    for r, line in enumerate(rows):
        for c, ch in enumerate(line):
            if ch == '#':
                out[(top + r) * 8 + c] = 0xFF
    return out


def emit(out, name, data):
    out.write("static const u8 %s[] = {\n" % name)
    for i in range(0, len(data), 8):
        out.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 8]) + ",\n")
    out.write("};\n\n")


def main(path):
    with open(path, "w") as out:
        out.write("/* Generated by ps5/lang/make_glyphs.py. Do not edit.\n"
                  " * The marks Spanish adds to the game's own letters. */\n"
                  "#ifndef PS5_GLYPHS_ES_H\n#define PS5_GLYPHS_ES_H\n\n")
        for name, rows in MAIN.items():
            emit(out, "ps5_mark_main_" + name, main_texture(rows, MAIN_TOP[name]))
        for name, rows in MENU.items():
            emit(out, "ps5_mark_menu_" + name, menu_texture(rows, MENU_TOP[name]))
        for code, (name, rows, top) in sorted(BUTTONS.items()):
            emit(out, "ps5_button_" + name, main_texture(rows, top))
        out.write("/* The character each one replaces, for ps5_lang.c. */\n"
                  "static const struct { u8 code; const u8 *glyph; } ps5_buttons[] = {\n")
        for code, (name, _rows, _top) in sorted(BUTTONS.items()):
            out.write("    { 0x%02X, ps5_button_%s },\n" % (code, name))
        out.write("};\n\n")
        out.write("#endif\n")
    print("%s: %d marks, %d buttons" % (path, len(MAIN) + len(MENU), len(BUTTONS)))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    main(sys.argv[1])
