#!/usr/bin/env python3
"""make_strings - the menus' Spanish text, as a table the game looks up in.

The game's menus print strings built from the macros in
include/text_strings.h, in dozens of places. Rather than change every one of
them, each English string is paired here with its translation, and the printing
and measuring functions look the string up (ps5_lang_string). Both sides are
encoded by the game's own textconv, so the comparison is over the bytes the
game itself holds.

    make_strings.py <strings_es.txt> <out .c.in>
"""
import re
import sys


def main(table_path, out_path):
    pairs = []
    for line in open(table_path, encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        macro, spanish = line.split('=', 1)
        pairs.append((macro.strip(), spanish.strip()))

    with open(out_path, 'w', encoding='utf-8') as out:
        out.write('/* Generated by ps5/lang/make_strings.py from strings_es.txt. Do not edit.\n'
                  ' * Each of the menus\' strings and its translation, in the game\'s encoding. */\n'
                  '#include "types.h"\n'
                  '#include "text_strings.h"\n'
                  '#include "ps5_lang.h"\n\n')
        for i, (macro, spanish) in enumerate(pairs):
            uncompressed = macro in ('TEXT_NORMAL_UPCLOSE', 'TEXT_NORMAL_FIXED')
            mark = '__' if uncompressed else '_'
            out.write('static const u8 en_%d[] = { %s };\n' % (i, macro))
            out.write('static const u8 es_%d[] = { %s("%s") };\n' % (i, mark, spanish.replace('"', '\\"')))
        out.write('\nconst struct Ps5LangString ps5_lang_strings[] = {\n')
        for i, (macro, _) in enumerate(pairs):
            out.write('    { en_%d, es_%d },   /* %s */\n' % (i, i, macro))
        out.write('};\n\nconst s32 ps5_lang_string_count = '
                  '(s32) (sizeof(ps5_lang_strings) / sizeof(ps5_lang_strings[0]));\n')
    print('%s: %d strings' % (out_path, len(pairs)))


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
