#!/usr/bin/env python3
"""make_strings - the menus' Spanish text, as a table the game looks up in.

The game's menus print strings built from the macros in
include/text_strings.h, in dozens of places. Rather than change every one of
them, each English string is paired here with its translation, and the printing
and measuring functions look the string up (ps5_lang_string). Both sides are
encoded by the game's own textconv, so the comparison is over the bytes the
game itself holds.

    make_strings.py <strings_es.txt> <out .c.in>
"""
import os
import re
import sys

# The game has three fonts, and only the dialogue one is complete. The coloured
# HUD font has just the letters the English text needs - no J, Q, V, X or Z -
# and the menus' small font has no lowercase. A character a font does not have
# is a null pointer the graphics processor then reads from, which crashes the
# console, so every string is checked here against the font that draws it.
#
# Which strings go to which font is decided by the calls in the game's own code
# (print_hud_lut_string and print_menu_generic_string).
HUD_STRINGS = {
    "TEXT_PAUSE", "TEXT_HUD_HI_SCORE", "TEXT_HI_SCORE", "TEXT_HUD_CONGRATULATIONS",
    "TEXT_SELECT_FILE", "TEXT_CHECK_FILE", "TEXT_COPY_FILE", "TEXT_ERASE_FILE",
    "TEXT_SOUND_SELECT", "TEXT_NEW", "TEXT_MARIO",
}
MENU_STRINGS = {
    "TEXT_MY_SCORE", "TEXT_MYSCORE", "TEXT_FILE_MARIO_A", "TEXT_FILE_MARIO_B",
    "TEXT_FILE_MARIO_C", "TEXT_FILE_MARIO_D",
}


def font_codes(path, table):
    """The character codes a font table actually has a glyph for, in the US
    build: the entries of the table that are not a null pointer."""
    lines = open(path).read().split("\n")
    i = next(n for n, l in enumerate(lines) if table + "[] = {" in l)
    block = []
    for line in lines[i:]:
        block.append(line)
        if line.startswith("};"):
            break
    text = "\n".join(block)
    marker = "#elif defined(VERSION_US)"
    if marker in text:
        us = text[text.find(marker) + len(marker):]
        for nxt in ("#elif", "#endif", "#else"):
            if nxt in us:
                us = us[:us.find(nxt)]
    else:
        us = text[text.find("#else") + 5:text.rfind("#endif")]
    entries = [e.strip() for e in re.sub(r"//.*", "", us).replace("\n", " ").split(",") if e.strip()]
    return {i for i, e in enumerate(entries) if e not in ("0x0", "0x00", "0")}


def encode(text, charmap):
    keys = sorted(charmap, key=len, reverse=True)
    out, i = [], 0
    while i < len(text):
        for k in keys:
            if text.startswith(k, i):
                out += charmap[k]
                i += len(k)
                break
        else:
            raise SystemExit("make_strings: no character %r in the charmap" % text[i])
    return out


def read_charmap(path):
    cm = {}
    for line in open(path, encoding="utf-8"):
        m = re.match(r"^'(.+?)'\s*=\s*(.+?)\s*(#.*)?$", line.strip())
        if m:
            cm[m.group(1).replace("\\'", "'")] = [int(x, 16) for x in m.group(2).replace(" ", "").split(",") if x]
    return cm


def check_fonts(pairs):
    here = os.path.dirname(os.path.abspath(__file__))     # ps5/lang
    root = os.path.abspath(os.path.join(here, "..", ".."))
    charmap = read_charmap(os.path.join(here, "charmap_es.txt"))
    fonts = {
        "the HUD font": (HUD_STRINGS, font_codes(os.path.join(root, "bin/segment2.c"), "main_hud_lut")),
        "the menus' small font": (MENU_STRINGS, font_codes(os.path.join(root, "levels/menu/leveldata.c"), "menu_font_lut")),
    }
    problems = []
    for macro, spanish in pairs:
        for font, (macros, codes) in fonts.items():
            if macro not in macros:
                continue
            for c in encode(spanish, charmap):
                if c not in codes and c not in (0x9E, 0xFF):
                    problems.append("%s: %r has a character %s cannot draw (0x%02X)" % (macro, spanish, font, c))
    if problems:
        raise SystemExit("make_strings: " + "\nmake_strings: ".join(problems))


def main(table_path, out_path):
    pairs = []
    for line in open(table_path, encoding='utf-8'):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        macro, spanish = line.split('=', 1)
        pairs.append((macro.strip(), spanish.strip()))

    check_fonts(pairs)

    with open(out_path, 'w', encoding='utf-8') as out:
        out.write('/* Generated by ps5/lang/make_strings.py from strings_es.txt. Do not edit.\n'
                  ' * Each of the menus\' strings and its translation, in the game\'s encoding. */\n'
                  '#include "types.h"\n'
                  '#include "text_strings.h"\n'
                  '#include "ps5_lang.h"\n\n')
        for i, (macro, spanish) in enumerate(pairs):
            uncompressed = macro in ('TEXT_NORMAL_UPCLOSE', 'TEXT_NORMAL_FIXED')
            mark = '__' if uncompressed else '_'
            out.write('static const u8 en_%d[] = { %s };\n' % (i, macro))
            out.write('static const u8 es_%d[] = { %s("%s") };\n' % (i, mark, spanish.replace('"', '\\"')))
        out.write('\nconst struct Ps5LangString ps5_lang_strings[] = {\n')
        for i, (macro, _) in enumerate(pairs):
            out.write('    { en_%d, es_%d },   /* %s */\n' % (i, i, macro))
        out.write('};\n\nconst s32 ps5_lang_string_count = '
                  '(s32) (sizeof(ps5_lang_strings) / sizeof(ps5_lang_strings[0]));\n')
    print('%s: %d strings' % (out_path, len(pairs)))


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(sys.argv[1], sys.argv[2])
